name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  test_CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: setup
        run: |
          make setup
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Run Test
        run: |
          make test
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: cc5fb311-3af7-4c2b-a3da-927bfa5a863e
